version: '3.5'

services:
  postgres:
    container_name: postgres_task_management
    image: postgres
    environment:
      POSTGRES_USER: tasks
      POSTGRES_PASSWORD: tasks
      POSTGRES_DB: tasks

    ports:
      - "5435:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

